"""questions table

Revision ID: 482ee302609e
Revises: 99e01f410b5d
Create Date: 2018-08-25 13:49:39.245341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482ee302609e'
down_revision = '99e01f410b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_timestamp'), 'question', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_timestamp'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###
